language: perl
cache:
  directories:
    # local::lib caching
    - $HOME/perl5
    - maint/cpanfile-git-log
matrix:
  include:
    - perl: "5.16"
      os: linux
      dist: trusty
      sudo: false
    - perl: "5.18"
      env: COVERAGE=1   # enables coverage+coveralls reporting
      os: linux
      dist: trusty
      sudo: false
    - perl: "5.20"
      os: linux
      dist: trusty
      sudo: false
    - perl: "blead"
      os: linux
      dist: trusty
      sudo: false
    - perl: "system"
      os: osx
  allow_failures:
    - perl: blead       # ignore failures for blead perl
sudo: false             # faster builds as long as you don't need sudo access
before_install:
  - export PERL_ALT_INSTALL=OVERWRITE
  - export DEVOPS_BRANCH="master"
  - eval "$(curl https://raw.githubusercontent.com/project-renard/devops/$DEVOPS_BRANCH/script/helper.pl | perl -- | awk '/^#START/,/^#END/ { print > "/dev/stdout"; next } { print > "/dev/stderr"}' )"

script:
  - perl Makefile.PL && make test
  - make install
  - export ARCHFLAGS='-arch x86_64';
  - "perl ./maint/install-zmq-libzmq.pl ZMQ::LibZMQ3"
  - "perl ./maint/install-zmq-libzmq.pl ZMQ::LibZMQ4"
