language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.22"
  - "blead"             # builds perl from git
matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1   # enables coverage+coveralls reporting
  allow_failures:
    - perl: blead       # ignore failures for blead perl
sudo: false             # faster builds as long as you don't need sudo access
before_install:
  - export PERL_ALT_INSTALL=OVERWRITE
  - export DEVOPS_BRANCH="master"
  - eval "$(curl https://raw.githubusercontent.com/project-renard/devops/$DEVOPS_BRANCH/script/helper.pl | perl -- | awk '/^#START/,/^#END/ { print > "/dev/stdout"; next } { print > "/dev/stderr"}' )"

script:
  - perl Makefile.PL && make test
  - make install
  - export ARCHFLAGS='-arch x86_64';
  - command cpanm --test-only ZMQ::LibZMQ3 --build-args 'OTHERLDFLAGS=' --verbose
