---
abstract: 'A replacement for Alien::ZMQ that uses Alien::ZMQ::latest'
author:
  - 'Zakariyya Mughal <zmughal@cpan.org>'
build_requires:
  Test::Most: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alt-Alien-ZMQ-Alien-ZMQ-latest
no_index:
  file:
    - lib/Alien/ZMQ.pm
requires:
  Alien::ZMQ::latest: '0'
  Text::ParseWords: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/zmughal/p5-Alt-Alien-ZMQ-Alien-ZMQ-latest
  repository: https://github.com/zmughal/p5-Alt-Alien-ZMQ-Alien-ZMQ-latest.git
version: '0.001'
x_serialization_backend: 'YAML::Tiny version 1.70'
